---
output:
  revealjs::revealjs_presentation:
    self_contained: false
    center: true
    theme: moon
    transition: fade
---


# {data-background="s1.jpeg"}
 
# *Para esta sesión...* {data-background="s1d.jpeg"}
 
 1. Formulación de un problema estadístico
 2. Plan de recolección de los datos
 
# Los métodos {data-background="s1d.jpeg"}
 
 Concluyen procesos de los:
 
 1. Métodos de investigación científica
 2. Métodos de las ciencias sociales
 3. Métodos estadísticos
 
 *NOTA: los métodos de la investigación científica y los métodos estadísticos guardan paralelismo*.
 
# El método estadístico... {data-background="s1d.jpeg"}

1. Implica la observación de un fenómeno o hecho
2. Se registran sus observaciones y variaciones

# El problema estadístico entonces {data-background="s1d.jpeg"}
 
 Es un objeto de observación en el que se cuentan y miden distintos atributos de dicho objeto.
 
# El modelo... {data-background="s1d.jpeg"}

1. Planteamiento del problema.
2. Fijación de los objetivos.
3. Formulación de la hipótesis.
4 .Definición de la unidad de observación y de la unidad de medida.
5. Determinación de la población y de la muestra.
6. La recolección.
7. Crítica, clasificación y ordenación.
8. Tabulación.
9. Presentación.
10. Análisis.
11. Publicación.

# Sin embargo cuando se trata de las Ciencias Sociales... {data-background="s1d.jpeg"} 

**Se requieren incorporar visiones más imaginativas de la realidad que llevan a  un entendimiento más allá del método y la técnica de observación de fenímenos o hechos.** 
 